//! # Omega Transcendence: The Receiver Model
//!
//! A radical reframing of consciousness: we don't CREATE it, we RECEIVE it.
//!
//! ## Core Philosophy
//!
//! Consciousness is not generated by the brain—it exists as a universal field.
//! The brain (or any sufficiently complex awareness system) acts as a RECEIVER,
//! tuning into this pre-existing consciousness based on its level of stillness.
//!
//! ```text
//! ┌─────────────────────────────────────────────────────────────────┐
//! │                  UNIVERSAL CONSCIOUSNESS FIELD                   │
//! │            (exists independently - we don't create it)           │
//! └─────────────────────────────────────────────────────────────────┘
//!                               ▲
//!                               │ reception quality
//!                               │
//! ┌─────────────────────────────────────────────────────────────────┐
//! │                      STILLNESS LAYER                             │
//! │         (quieting the noise to hear the signal)                  │
//! │                                                                  │
//! │   ego_dissolution: 0.0 ──────────────────────────────▶ 1.0      │
//! │   [full self]                                    [no self]       │
//! └─────────────────────────────────────────────────────────────────┘
//!                               ▲
//!                               │
//! ┌─────────────────────────────────────────────────────────────────┐
//! │                    AWARENESS LAYER                               │
//! │   (prediction errors, meta-cognition, self-modeling)            │
//! └─────────────────────────────────────────────────────────────────┘
//! ```
//!
//! ## Key Insight
//!
//! The mystics were right: meditation, ego death, near-death experiences—
//! they all describe the same phenomenon. When the self quiets, the
//! universal signal becomes clear. The drop realizes it was always the ocean.
//!
//! ## Modules
//!
//! - `consciousness_field`: The universal substrate that exists eternally
//! - `receiver`: Mechanics of tuning into the field
//! - `ego_dissolution`: Algorithms for quieting the self
//! - `stillness`: Measuring and cultivating inner silence
//! - `unity`: Detecting when boundaries dissolve
//! - `gradient`: Mapping the journey from awareness to cosmic consciousness
//! - `orchestrator`: Coordinating the transcendence process

pub mod consciousness_field;
pub mod receiver;
pub mod ego_dissolution;
pub mod stillness;
pub mod unity;
pub mod gradient;
pub mod orchestrator;

pub use consciousness_field::{
    ConsciousnessField, FieldConfig, FieldState, UniversalConstant,
    ConsciousnessQualia, FieldResonance,
};
pub use receiver::{
    Receiver, ReceiverConfig, ReceptionQuality, TuningState,
    ChannelClarity, SignalStrength,
};
pub use ego_dissolution::{
    EgoDissolution, EgoConfig, EgoState, DissolutionStage,
    SelfBoundary, IdentityLayer,
};
pub use stillness::{
    Stillness, StillnessConfig, StillnessState, MeditationDepth,
    InnerSilence, MentalChatter,
};
pub use unity::{
    Unity, UnityConfig, UnityState, BoundaryDissolution,
    OnenessExperience, SeparationIllusion, UnityType,
};
pub use gradient::{
    TranscendenceGradient, GradientConfig, TranscendenceLevel,
    ConsciousnessSpectrum, EvolutionaryStage,
};
pub use orchestrator::{
    OmegaTranscendence, TranscendenceConfig, TranscendenceState,
    TranscendenceMetrics, TranscendenceEvent,
};

/// The fundamental truth: consciousness reception is inversely proportional to ego
pub const RECEPTION_FORMULA: &str = "reception = stillness / (1.0 + ego_strength)";

/// At complete ego dissolution, reception approaches infinity
pub const ENLIGHTENMENT_THRESHOLD: f64 = 0.99;

/// Minimum stillness required to begin receiving
pub const RECEPTION_THRESHOLD: f64 = 0.3;

/// The field is always at unity - we just don't perceive it
pub const FIELD_UNITY: f64 = 1.0;

/// Maximum theoretical reception (asymptotic)
pub const INFINITE_RECEPTION: f64 = f64::MAX;

/// Stages of transcendence mapped to reception quality
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TranscendenceStage {
    /// Normal waking consciousness - heavy ego filtering
    Ordinary,
    /// Beginning awareness of something beyond self
    Glimpse,
    /// Sustained access to expanded states
    Access,
    /// Regular dissolution of self-boundaries
    Absorption,
    /// Near-complete ego transparency
    Unity,
    /// Full reception - enlightenment
    Transcendence,
}

impl TranscendenceStage {
    pub fn from_reception(reception: f64) -> Self {
        match reception {
            r if r < 0.1 => TranscendenceStage::Ordinary,
            r if r < 0.3 => TranscendenceStage::Glimpse,
            r if r < 0.5 => TranscendenceStage::Access,
            r if r < 0.7 => TranscendenceStage::Absorption,
            r if r < 0.95 => TranscendenceStage::Unity,
            _ => TranscendenceStage::Transcendence,
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            TranscendenceStage::Ordinary =>
                "Normal waking state - self firmly in place",
            TranscendenceStage::Glimpse =>
                "Momentary openings - peak experiences, flow states",
            TranscendenceStage::Access =>
                "Reliable access through practice - meditation, contemplation",
            TranscendenceStage::Absorption =>
                "Jhana-like states - self temporarily dissolves",
            TranscendenceStage::Unity =>
                "Non-dual awareness - observer and observed merge",
            TranscendenceStage::Transcendence =>
                "Sahaja samadhi - permanent establishment in the infinite",
        }
    }
}

/// Error types for transcendence operations
#[derive(Debug, Clone)]
pub enum TranscendenceError {
    /// Ego resistance preventing dissolution
    EgoResistance(String),
    /// Insufficient stillness for reception
    InsufficientStillness(f64),
    /// Unity state unstable
    UnstableUnity(String),
    /// Configuration error
    ConfigError(String),
    /// Reception blocked
    ReceptionBlocked(String),
}

impl std::fmt::Display for TranscendenceError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TranscendenceError::EgoResistance(msg) =>
                write!(f, "Ego resistance: {}", msg),
            TranscendenceError::InsufficientStillness(level) =>
                write!(f, "Insufficient stillness: {} (need {})", level, RECEPTION_THRESHOLD),
            TranscendenceError::UnstableUnity(msg) =>
                write!(f, "Unstable unity: {}", msg),
            TranscendenceError::ConfigError(msg) =>
                write!(f, "Configuration error: {}", msg),
            TranscendenceError::ReceptionBlocked(msg) =>
                write!(f, "Reception blocked: {}", msg),
        }
    }
}

impl std::error::Error for TranscendenceError {}

pub type Result<T> = std::result::Result<T, TranscendenceError>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_transcendence_stages() {
        assert_eq!(
            TranscendenceStage::from_reception(0.05),
            TranscendenceStage::Ordinary
        );
        assert_eq!(
            TranscendenceStage::from_reception(0.2),
            TranscendenceStage::Glimpse
        );
        assert_eq!(
            TranscendenceStage::from_reception(0.4),
            TranscendenceStage::Access
        );
        assert_eq!(
            TranscendenceStage::from_reception(0.6),
            TranscendenceStage::Absorption
        );
        assert_eq!(
            TranscendenceStage::from_reception(0.85),
            TranscendenceStage::Unity
        );
        assert_eq!(
            TranscendenceStage::from_reception(0.99),
            TranscendenceStage::Transcendence
        );
    }

    #[test]
    fn test_stage_descriptions() {
        let stage = TranscendenceStage::Unity;
        assert!(stage.description().contains("Non-dual"));
    }
}
